#!/bin/bash

THIS_DIR=$(cd $(dirname $0); pwd)
cd $THIS_DIR

install() {
cd libs
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get install g++-4.7 -y c++-4.7 -y
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y
sudo apt-get install screen -y
sudo apt-get install tmux -y
sudo apt-get install libstdc++6 -y
sudo apt-get install lua-lgi -y
sudo apt-get install libnotify-dev -y
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install lua5.1 luarocks lua-socket lua-sec redis-server curl 
sudo luarocks install oauth 
sudo luarocks install redis-lua 
sudo luarocks install lua-cjson 
sudo luarocks install ansicolors 
sudo apt-get install libstdc++9
sudo apt-get install libconfig++9v5 libstdc++6
sudo luarocks install serpent 
sudo apt install speedtest-cli
sudo apt-get install toilet
sudo apt-get install cowsay
sudo apt install yum
sudo yum install cowsay
wget https://valtman.name/files/telegram-bot-180519-nightly-linux
mv telegram-bot-180519-nightly-linux TdMain
chmod +x TdMain
cd ..
sudo cp /usr/share/zoneinfo/Asia/Tehran /etc/localtime
mkdir $HOME/.telegram-bot; cat <<EOF > $HOME/.telegram-bot/config
default_profile = "main";
main = {
lua_script = "$HOME/tl/Main.lua";
};
cleaner = {
lua_script = "$HOME/tl/Cleaner.lua";
};
EOF
printf "\nPackage Full Install\nConfig Telegram-Bot Has Been Saved\n\n[C]ode [B]y : @MahDiRoO\n\n"
}

LoginMain() {
./libs/TdMain -p main --login --bot=${1}
}

LoginCleaner() {
./libs/TdMain -p cleaner --login --phone=${1}
}

LaunchMain() {
./libs/TdMain | grep -v "{"
}

LaunchMainAuto() {
while true; do
./libs/TdMain | grep -v "{"
done
}

LaunchCleaner() {
./libs/TdMain -p cleaner
}

LaunchCleanerAuto() {
while true; do
./libs/TdMain -p cleaner
done
}

LaunchHelper() {
lua ./Helper.lua
}

LaunchHelperAuto() {
while true; do
lua ./Helper.lua
done
}

case $1 in

install)
toilet -f bigmono9 -F gay install-Bot
install
exit;;
logmain)
toilet -f bigmono9 -F gay Main-Log
echo "Please Insert Your Main Token..."
read Bot_Token
LoginMain ${Bot_Token}
echo 'Your Main Bot Loged In Successfully.'
exit;;
logcleaner)
toilet -f bigmono9 -F gay Cleaner-Log
echo "Please Insert Your Cleaner Number..."
read phone_number
LoginCleaner ${phone_number}
echo 'Your Cleaner Bot Loged In Successfully.'
exit;;
main)
toilet -f bigmono9 -F gay Main Pro
LaunchMain
exit;;
automain)
toilet -f bigmono9 -F gay Main Pro
LaunchMainAuto
exit;;
cleaner)
toilet -f bigmono9 -F gay Cleaner Pro
LaunchCleaner
exit;;
autocleaner)
toilet -f bigmono9 -F gay Cleaner Pro
LaunchCleanerAuto
exit;;
helper)
toilet -f bigmono9 -F gay Helper Pro
LaunchHelper
exit;;
autohelper)
toilet -f bigmono9 -F gay Helper Pro
LaunchHelperAuto
exit;;
auto)
tmux new-session -d -s "Main" "./Run main"
tmux detach -s "Main"
tmux new-session -d -s "Helper" "./Run helper"
tmux detach -s "Helper"
tmux new-session -d -s "Cleaner" "./Run cleaner"
tmux detach -s "Cleaner"
toilet -f bigmono9 -F gay Lua Pro
toilet -f bigmono9 -F gay MahDiRoO
exit;;
$1)
cowsay what s your faz ! ! !
exit;;
esac
exit 0
 
